[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
thiserror.workspace = true
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
